default_platform(:ios)

platform :ios do
  desc "Build unsigned IPA and upload to Firebase"
  lane :firebase_beta do
    setup_ci

    xcode_select "/Applications/Xcode_16.4.app" # force correct version

    build_app(
      scheme: "WeatherHistory",
      project: "WeatherHistory.xcodeproj",  # explicitly point to project
      export_method: "ad-hoc",
      skip_codesigning: true,
      skip_package_ipa: false,
      output_directory: "build",
      output_name: "WeatherHistory.ipa"
    )

    firebase_app_distribution(
      app: ENV["FIREBASE_APP_ID_IOS"],
      testers: "youremail@gmail.com",
      release_notes: "CI build from GitHub Actions 🚀",
      firebase_cli_token: ENV["FIREBASE_TOKEN"],
      ipa_path: "build/WeatherHistory.ipa"
    )
  end
end
