
name: iOS CI (Firebase)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app/Contents/Developer

      - name: Install Ruby and Fastlane
        run: gem install fastlane --user-install

      - name: Build and upload to Firebase
        env:
          FIREBASE_APP_ID_IOS: ${{ secrets.FIREBASE_APP_ID_IOS }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: ~/.gem/ruby/*/bin/fastlane firebase_beta
