name: iOS Build & Deploy to Firebase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
      # ✅ Step 1: Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ Step 2: Set up Ruby and install Fastlane
      - name: Set up Ruby and Fastlane
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
      - name: Install Fastlane
        run: |
          gem install fastlane --no-document
          which fastlane
          fastlane --version

      # ✅ Step 3: Install CocoaPods (if needed)
      - name: Install CocoaPods
        run: |
          brew install cocoapods || true
          pod install || true

      # ✅ Step 4: Build your app
      - name: Build iOS app
        run: |
          xcodebuild -scheme WeatherHistory \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            clean build

      # ✅ Step 5: (Optional) Run Tests
      - name: Run tests
        run: |
          xcodebuild test -scheme WeatherHistory \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15'

      # ✅ Step 6: Deploy using Fastlane (only if Firebase configured)
      - name: Deploy to Firebase App Distribution
        if: ${{ secrets.FIREBASE_TOKEN != '' }}
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_APP_ID_IOS: ${{ secrets.FIREBASE_APP_ID_IOS }}
        run: |
          fastlane firebase_beta
